version: "3"

services:
  app:
    container_name: envhub
    network_mode: host
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - app:/app
    environment:
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET:
      JWT_SECRET:
      ROW_KEY_SECRET:
    links:
      - db

  db:
    image: postgres:14-alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: envhub
      POSTGRES_HOST: localhost
    ports:
      - 5432:5432
    volumes:
      - ./tmp/data:/var/lib/postgresql/data

volumes:
  app:
