version: "3"

services:
  app:
    container_name: envhub
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    environment:
      MYSQL_DSN: "envhubuser:envhubpassword@tcp(db)/envhub?interpolateParams=true"
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET:
      JWT_SECRET:
      VARIABLE_KEY:
      USER_TOKEN_KEY:
      USER_ID_KEY:
    links:
      - db

  db:
    container_name: envhub-db
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: envhub
      MYSQL_USER: envhubuser
      MYSQL_PASSWORD: envhubpassword
    ports:
      - 3306:3306
    volumes:
      - ../tmp/data:/var/lib/mysql
